
stages:
  - test

test-zambeze:
  stage: test
  tags:
    - cades
  script:
    - /opt/anaconda3/bin/python3 -m pip install -r requirements.txt
    - chmod 600 $ZAMBEZE_CI_TEST_RSYNC_SSH_KEY
    - /opt/anaconda3/bin/python3 -m pytest -m unit -sv
    - /opt/anaconda3/bin/python3 -m pytest -m gitlab_runner -sv
