
stages:
  - test
  - run

test-zambeze:
  stage: test
  tags:
    - cades
  script:
    - python3.9 -m venv ./zambeze-py39-env
    - source ./zambeze-py39-env/bin/activate
    - python3.9 -m pip uninstall -y zambeze
    - python3.9 -m pip install -r requirements.txt
    - python3.9 -m pip install .
    - chmod 600 $ZAMBEZE_CI_TEST_RSYNC_SSH_KEY
    - python3.9 -m pytest -m gitlab_runner -sv

# Ideally this job would use a virtual environment that was provisioned by 
# Ansible, as it is, if the VM goes down this venv disappears
test-zambeze-globus:
  stage: test
  tags:
    - globus
  script:
    - python3.9 -m venv ./zambeze-py39-env
    - source ./zambeze-py39-env/bin/activate
    - env
    - python3.9 -m pip uninstall -y zambeze
    - python3.9 -m pip install -r requirements.txt
    - python3.9 -m pip install .
    - python3.9 -m pytest -m globus -sv
    - echo "globus.token file must exist already to prevent hanging"
    - python3.9 -m pytest -m globus_native -sv
