
stages:
  - test

test-zambeze:
  stage: test
  tags:
    - cades
  script:
    - /opt/anaconda3/bin/python3 -m pip install -r requirements.txt
    - chmod 600 $ZAMBEZE_CI_TEST_RSYNC_SSH_KEY
    - /opt/anaconda3/bin/python3 -m pytest -m unit -sv
    - /opt/anaconda3/bin/python3 -m pytest -m gitlab_runner -sv

# Ideally this job would use a virtual environment that was provisioned by 
# Ansible, as it is, if the VM goes down this venv disappears
test-zambeze-globus:
  stage: test
  tags:
    - globus
  script:
    - source /home/gitlab-runner/py-venv-3.9/bin/activate
    - python3 -m pip install -r requirements.txt
    - python3 -m pytest -m unit -sv
    - python3 -m pytest -m globus -sv
