version: '3.8'
name: zambeze
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
    - 5672:5672
    - 15672:15672

  zambeze_agent1:
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      PYTHONWARNINGS: "ignore::DeprecationWarning"
    container_name: zambeze1
    image: zambeze/zambeze:latest
    # Uncomment volumes if you want to sync your local dev. disk with the container's.
#    volumes:
#      - ../db:/zambeze/db
#      - ../:/zambeze
    command: [/bin/sh, -c, 'sleep 10 && zambeze agent start & sleep 2 && tail -f /root/.zambeze/logs/`ls -t /root/.zambeze/logs/ | head -n 1`']
    depends_on:
      -  rabbitmq
    ports:
      - 22:22

  zambeze_agent2:
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      PYTHONWARNINGS: "ignore::DeprecationWarning"
      ZAMBEZE_CI_TEST_RSYNC_IP: zambeze_agent1
      ZAMBEZE_CI_TEST_RSYNC_SSH_KEY: "null"
    container_name: zambeze2
    image: zambeze/zambeze:latest
#    volumes:
#      - ../db:/zambeze/db
#      - ../:/zambeze
    command: [/bin/sh, -c , 'echo "Im idle!" & tail -f /dev/null']
    depends_on:
      -  zambeze_agent1 # Needed when launching command on startup
