# Compose a RabbitMQ and Zambeze multi-container application stack
#
# Run the application stack
# docker compose --file deployment/compose-rabbit.yml up
#
# Run the application stack in detached mode
# docker compose --file deployment/compose-rabbit.yml up -d
#
# Tear down the application stack
# docker compose --file deployment/compose-rabbit.yml down

name: zambezeapp

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 3

  zambezeagent:
    image: zambeze
    container_name: zambeze-agent
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
    command: zambeze agent start
