version: '3.8'
services:
  nats:
    container_name: nats
    image: nats
    command: -V
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  zambeze_agent1:
    environment:
      NATS_HOST: nats
      NATS_PORT: 4222
      PYTHONWARNINGS: "ignore::DeprecationWarning"
    container_name: zambeze1
    image: zambeze/zambeze:latest
    command: [/bin/sh, -c, 'zambeze agent start & sleep 2 && tail -f /root/.zambeze/logs/`ls -t /root/.zambeze/logs/ | head -n 1`']
    depends_on:
      -  nats

  zambeze_agent2:
    environment:
      NATS_HOST: nats
      NATS_PORT: 4222
      PYTHONWARNINGS: "ignore::DeprecationWarning"
    container_name: zambeze2
    image: zambeze/zambeze:latest
    #tty: true
    #stdin_open: true
#    volumes:
#      - ../db:/zambeze/db
#      - ../:/zambeze  # This line is needed only for development.
    command: [/bin/sh, -c , 'echo "Im idle!" & tail -f /dev/null']
    depends_on:
      -  zambeze_agent1 # Needed when launching command on startup
