name: Internal Integration Tests
on: [push, pull_request]

jobs:
  rsync_example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Zambeze image
      run: docker build -t zambeze/zambeze -f deployment/Dockerfile .
    - name: Launch Docker Compose
      run: docker compose -f deployment/compose-rabbit.yml up -d
    - name: Sleep 
      run: |
        echo "I'm going to sleep hoping the services will be up when I wake up... zzz..."
        sleep 15
    - name: Generating SSH Keys
      run: |
        ssh-keygen 
    - name: Run Tests
      run: |
        export ZAMBEZE_CI_TEST_RSYNC_IP="null"
        export ZAMBEZE_CI_TEST_RSYNC_SSH_KEY="null"
        docker compose -f deployment/compose-rabbit.yml exec zambeze_agent2 python3 -m pytest -m integration -vs
    - name: Cleanup
      run: docker compose -f deployment/compose-rabbit.yml down
