name: Pylint

on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.16.1
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --recursive=y --disable=missing-module-docstring --disable=missing-class-docstring --disable=missing-function-docstring .
