name: Pytest tests

on: [push, pull_request]

jobs:
  pytest-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install zambeze and dependencies
        run: pip install .[dev]

      - name: Run tests
        run: pytest -m unit --cov=zambeze tests/

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
