name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Check python version
      run: python --version
    - name: Install our dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup compose
      if: github.ref == 'refs/heads/main'
      run: |
        docker compose -f deployment/compose.yml up
        sleep(5)
        docker compose -f deployment/compose.yml zambeze_agent2 python3 -m pytest -m integration -sv 
        docker compose -f deployment/compose.yml down
