name: Unit Tests

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Update ubuntu
        run: sudo apt-get update

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-sphinx sphinx-rtd-theme-common
          pip install sphinx_rtd_theme recommonmark flake8 pytest pytest-cov

      - name: Check package install
        run: |
          pip install .[dev]

      - name: Run tests
        run: |
          pytest -m unit --cov=zambeze tests/

      - name: Upload Coverage to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v2

      - name: Build documentation
        run: |
          cd docs
          pip install -r requirements.txt
          make html
